### ISSUE TITLE
Auto-reconnect when disconnected?

### ISSUE THREAD

**Issue by craysiii** [faye/faye-websocket-ruby#121]
Sorry if there is something I am missing that is obvious, but I am unable to find any information in the documentation or the code that would allow for reconnecting an instance of the client after an unintentional disconnect.

I am using EM and Faye::Websocket to operate chat bots, and sometimes the vps that I host on temporarily loses connection. For now I am having to manually restart, wondering if there is something that could be done about this.

Thanks in advance.

**Comment by jcoglan** [comment]
We do not automatically reconnect WebSockets, for two reasons.

First, it does not match the behaviour of the browser implementation, which this library and its node.js counterpart are intended to be API-compatible with.

Second, it is often not safe for a WebSocket to implicitly reconnect without notifying the application, because some other app-level error recovery might be needed. For example, Faye (the product this library was extracted from) needs to re-send any messages that were not acknowledged at the time the socket was dropped.

This differs from other protocols like Server Sent Events, which has a built-in way for the client to tell the server the ID of the last message it received, so the server can resume from there. WebSocket has no such mechanism so more application-level control is needed.

**Comment by craysiii** [comment]
Thanks for the info, after much thought I will just return non-zero exit code and let dokku restart automatically based on that.
