### ISSUE TITLE
Documentation scattered

### ISSUE THREAD

**Issue by Cyken-Zeraux** [faye/faye-websocket-ruby#77]
Recently was trying out the examples for this library and saw that the examples are all piled into one folder, being 'root/examples', along with requiring files from 'root/spec'. Each example should have its own folder, and be detached from root/spec if possible, so one or two files can be downloaded by themselves and ran.

 I think this would increase usability for new users, and of course improve cleanliness.

**Comment by jcoglan** [comment]
This is possibly a case of false advertising... I suppose over time they've become more like examples for testing rather than documentation; most of them support the [pre-release tests](https://github.com/faye/wstest).

Most of the examples are interrelated as well, so I'm not sure they could all be separated into different directories. Here's what each file does:

* `app.rb` - a Rack app that supports WebSocket and EventSource and serves the pages `ws.html` and `sse.html`
* `autobahn_client.rb` - the script that runs the client-side Autobahn tests
* `client.rb` - an example client that can connect to any endpoint
* `config.ru` - the config for running `app.rb` via `rackup(1)`
* `haproxy.conf` - a HAProxy config for running along with the server example
* `proxy_server.rb` - spins up a proxy server for use with the server and client examples, uses the `ProxyServer` class from the tests
* `rainbows.conf` - config for running the server example using Rainbows
* `server.rb` - a script that runs `app.rb` using various Ruby app servers
* `sse.html`, `ws.html` - static pages for testing the server via the browser's built-in `WebSocket` and `EventSource` clients

The only file that's not designed primarily to interact with the others is `autobahn_client.rb`; the others are all interrelated although some (e.g. `client.rb`) can connect to other servers.

The examples load code from the tests when that code is also used by the tests; any code that's needed by the tests is with the tests, and the examples reuse some of that.

Given the above, would it still make sense to separate things (given the pre-release tests rely on the current location of the examples)? Do the examples offer any value beyond what's in the documentation?

**Comment by jcoglan** [comment]
I'm going to close this issue because I've had no feedback on my previous comments, but please do re-open it if you have further remarks.
