### ISSUE TITLE
Performance limitations on running faye-websocket-ruby behind thin?

### ISSUE THREAD

**Issue by fields** [faye/faye-websocket-ruby#84]
Hi - we're running faye-websocket-ruby behind thin, and hitting Service Unavailable errors under load. thin.yml should have plenty of connections to serve these requests - what other parameters may be limiting this?

Are any of the other deployment options more recommended for deploying services under load?

**Comment by jcoglan** [comment]
I typically don't give out one-size-fits-all recommendations since this largely depends on your environment and application traffic patterns.

This gem does also support Goliath, Passenger, Puma and Rainbows, and any server that supports `rack.hijack`. Have you tried any of those for serving your application? Are you able to scale horizontally by adding more backends?

**Comment by jcoglan** [comment]
@fields Do you have any further comments on my questions, or should I close this issue?
