### ISSUE TITLE
faye websocket is already in closing or closed state

### ISSUE THREAD

**Issue by pvin** [faye/faye-websocket-ruby#90]
Hi im using faye-websocket-ruby

After few seconds shows me that "  faye websocket is already in closing or closed state  "
So what should I do for keep listing or keeping my websocket open till the page close.

Found this link https://github.com/faye/faye/commit/72a6d4d2fcfc4e8be730892ca0109dd09d96b5fa

Here file called javascript/transport/web_socket.js has some fix where can i find this file in faye-websocket-ruby gem ?

Any help here?

Thank you

**Comment by jcoglan** [comment]
I'm sorry, I don't know what you mean. The commit you link to is in functionality that's unrelated to this repository, since it's JavaScript code that interacts with the built-in browser `WebSocket` class.

If you need the fix in that commit, it will appear in a future release of the `faye` gem, not `faye-websocket-ruby`.

**Comment by pvin** [comment]
Hi im using faye-websocket-ruby

After few seconds shows me that " faye websocket is already in closing or closed state "
So what should I do for keep listing or keeping my websocket open till the page close.

**Comment by pvin** [comment]
Added my code here

**my view file**

html.....
...........
 <script>
      $(function () {
        var xx_id = xx;
        var yy_id = yyy;
        var form = $('#<%= xx.id %>');
        var auctionSocket = new AuctionSocket(
          xx_id,
          yy_id,
          form
          );
      });
      App = {
        websocket_url: "ws://<%= request.host%>:<%= request.port%>/"
      };
    </script>

**js file**


var AuctionSocket = function(xx_id, yy_id, form) {
    this.xx_id = xx_id;
    this.yy_id = yy_id;
    this.form = $(form);
    this.socket = new WebSocket(App.websocket_url + "auctions/" + this.xx_id);
    this.initBinds();
};

AuctionSocket.prototype.initBinds = function() {
    var _this = this;
    this.form.submit(function(e) {
        e.preventDefault();
       zz = parseFloat(_this.form.find("#zz_price").val()); 
       _this.sendBid(zz);
    });


AuctionSocket.prototype.sendBid = function(value) {
    this.value = value;
    var template = "test  {{xx_id}} {{yy_id}} {{some value}}"
    this.socket.send(Mustache.render(template, {
        xx_id: this.user_id,
        yy_id: this.auction_id,
        value: value
    }));
};


 this.socket.onmessage = function(e) {
        var tokens = e.data.split(" ");
         do somithing;
};

**Comment by pvin** [comment]
hi I follow this tut 
https://github.com/josemotanet/tutsplus-awections/blob/master/app/assets/javascripts/auction_websocket.js

**Comment by jcoglan** [comment]
I'll try to clear up some confusion about these gems, I hope this is helpful.

`faye-websocket` is *just* a WebSocket implementation; in your project it's handling the server side of the WebSocket connection while your code directly uses the built-in browser `WebSocket` class. `faye-websocket` does not provide any JS code for interacting with sockets in the browser.

`faye` is a messaging system build *on top* of WebSocket (and other things). It has a server-side component (that uses `faye-websocket` internally) and a JavaScript client-side component. The Faye JS client manages WebSocket connections internally, making sure they reconnect and redeliver failed messages.

Since you're interacting with WebSocket directly in the browser, you need to handle reconnection and any redelivery needed by your application yourself. The commit you linked to in `faye` is out of scope for the project you're working on.

**Comment by pvin** [comment]
@jcoglan Thanks for your valuable time and explanation. 
Yes I am getting that point. We thought   faye-websocket-ruby on top of faye so  js file may exist.
now I am clear and fixed the actual issue.(port 9292 was blocked in server) 

Thank you
