### ISSUE TITLE
Takes 60 seconds to detect a hard disconnect despite 10 second ping

### ISSUE THREAD

**Issue by andrewhamon** [faye/faye-websocket-ruby#93]
Hello there!

I am (attempting) to use websockets for some basic presence detection.

In my testing, one of the first things I set out to determine was what happens during a hard TCP disconnect - i.e. etherent cable unplugged.

I configured `ping` to be 10 seconds like so: `ws = Faye::WebSocket.new(env, nil, {ping: 10 })`

Yet it seems to consistently take 60 seconds for the `close` callback to fire in such a situation.

I'm connecting directly to the Ruby server (in this case Puma) with no intermediary proxies.

Any ideas or other tests I should run?

**Comment by jcoglan** [comment]
Ping is not used by Faye::WebSocket itself to test presence, it merely makes the socket send ping frames at that rate. It's intended to be used to keep connections open when going through proxies that disconnect if no data is transferred for too long.

**Comment by andrewhamon** [comment]
My apologies, somehow I managed to post the initial issue before I had even finished typing it!

**Comment by andrewhamon** [comment]
Are you familiar with any common patterns used by this library (or websockets in general) to quickly detect a disconnect?

Theres `ws.ping` which takes a callback for the ping, but what would make this really handy would be `ws.ping` with a configureable timeout and a block to handle that timeout.

**Comment by andrewhamon** [comment]
I ended up doing something like this:

```ruby
pinger = EventMachine::PeriodicTimer.new(5) do
  timeouter = EventMachine::Timer.new(2) do
    pinger.cancel
    ws.close
    # My app logic here
  end

  ws.ping 'detecting presence' do
    timeouter.cancel
  end
end
```

**Comment by jcoglan** [comment]
That's pretty much what I was going to suggest. Faye's general policy is to make a best effort attempt at delivery and error detection given the platform it's running on. In this case, it will report a socket closed as and when EventMachine calls `unbind` on the connection, but if it doesn't get called Faye has no idea there's a problem.

Ping/pong as a healthcheck on the remote peer is not implemented because it tends to be application/context dependent. e.g. if a ping frame is buffered behind a large message on the client side (either in kernel buffers or in app code), or sent via a slow connection, the client might be fine but the server might decide it's dead and disconnect from it if your timeout is too short.

Or, you might implement error detection/recovery in your app that's built on top of WebSocket, making extra robustness in the WebSocket implementation redundant. So, like I say, we make a best effort here without doing anything that would make the code more complex or introduce features outside those required by the spec.
