### ISSUE TITLE
Reconnection mechanism for WebSocket::Client

### ISSUE THREAD

**Issue by wpp** [faye/faye-websocket-ruby#98]
Hi!

First of all: Sorry for opening an Issue since this is actually more of a question.

I'm wondering if there is a `reconnect/retry` option for the `WebSocket::Client` (similar to the `retry` `EventSource`)? As in: once the client receives `close` the library would try to reconnect x times every y seconds. (Or something similar).

I've [searched previously opened issues](https://github.com/faye/faye-websocket-ruby/issues?utf8=✓&q=reconnect) for a retry/reconnect mechanism in the WebSocket::Client but didn't really find an answer.

**Comment by jcoglan** [comment]
We don't offer this functionality, primarily because this library aims to replicate that available in the browser. But comparing it to EventSource is interesting and made me think about *why* this functionality exists there but not in WebSocket.

Typically, if you have a network disconnection, the application needs to recover in some way, e.g. by re-establishing subscriptions to channels (in a system like Bayeux or ActionCable), or by re-sending unacknowledged messages, and so on. If the network abstraction transparently reconnects and gives no hint to the application about what it's done, the application will lose messages.

EventSource has a built-in mechanism for handling this: the server can annotate each message with an ID, and when the client reconnects, it includes a header stating the last ID it received. In this way, the server knows what to re-send.

WebSocket is more complicated in that it works in two directions (EventSource is just server to client), and it doesn't have any integration with the application layer in terms of reporting which messages were received by the other peer.

All of which is to say that most apps will need to handle disconnections themselves, and that's why we don't offer that functionality.

**Comment by wpp** [comment]
Thank you so much for that elaborate answer.
